#!/bin/sh

# move kernel and copy Gateway dtb to FAT partition after kernel update
if [ -f /boot/kernel/kernel.bin ]; then
    INSTALLED_KERNEL=$(cat /usr/local/opnsense/version/kernel)
    if [ "${INSTALLED_KERNEL}" != "26.1.3" ]; then
        cp /boot/msdos/kernel.img /boot/msdos/kernel.old
        mv /boot/kernel/kernel.bin /boot/msdos/kernel.img
        cp /boot/msdos/dtb/mono-gateway-dk.dtb /boot/msdos/dtb/mono-gateway-dk.old
        cp /boot/dtb/freescale/mono-gateway-dk.dtb /boot/msdos/dtb/
    fi
fi
