# libfci - FCI userspace library for FreeBSD
#
# Copyright 2026 Mono Technologies Inc.
# SPDX-License-Identifier: BSD-2-Clause

LIB=		fci
SHLIB_MAJOR=	1
SRCS=		libfci_freebsd.c
INCS=		libfci.h

CFLAGS+=	-I${.CURDIR}/../fci

.include <bsd.lib.mk>
